#import userFragment from "../fragments/fragments.gql"

query Waiting($input: GameInput!) {
  game(input: $input) {
    id
    slug
    status
    host {
      ...userFragment
    }
    players {
      user {
        ...userFragment
      }
    }
  }
}
